---
- name: Pull docker image
  docker_image: 
    name: nginx
    source: pull
    tag: latest

- name: Install nginx
  community.docker.docker_container:
    image: nginx:latest
    name: nginx
    exposed_ports: 80
    state: started