---
- name: Setup server stack
  hosts: all
  become: true

  tasks:
  - name: Install apache
    dnf:
      name: httpd
      state: present

  - name: Ensure Apache is started and enabled
    service:
      name: httpd
      state: started
      enabled: true
